/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/_menu'
import { Route as MenuIndexRouteImport } from './routes/_menu/index'
import { Route as MenuProfileRouteImport } from './routes/_menu/profile'
import { Route as MenuPluginsIndexRouteImport } from './routes/_menu/plugins/index'
import { Route as MenuPluginsCreateRouteImport } from './routes/_menu/plugins/create'
import { Route as MenuPluginsPluginIdPluginRouteImport } from './routes/_menu/plugins/$pluginId/_plugin'
import { Route as MenuPluginsPluginIdPluginSettingsRouteImport } from './routes/_menu/plugins/$pluginId/_plugin/settings'

const MenuPluginsPluginIdRouteImport = createFileRoute(
  '/_menu/plugins/$pluginId',
)()

const MenuRoute = MenuRouteImport.update({
  id: '/_menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuProfileRoute = MenuProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MenuRoute,
} as any)
const MenuPluginsPluginIdRoute = MenuPluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => MenuRoute,
} as any)
const MenuPluginsIndexRoute = MenuPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuPluginsCreateRoute = MenuPluginsCreateRouteImport.update({
  id: '/plugins/create',
  path: '/plugins/create',
  getParentRoute: () => MenuRoute,
} as any)
const MenuPluginsPluginIdPluginRoute =
  MenuPluginsPluginIdPluginRouteImport.update({
    id: '/_plugin',
    getParentRoute: () => MenuPluginsPluginIdRoute,
  } as any)
const MenuPluginsPluginIdPluginSettingsRoute =
  MenuPluginsPluginIdPluginSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MenuPluginsPluginIdPluginRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile': typeof MenuProfileRoute
  '/': typeof MenuIndexRoute
  '/plugins/create': typeof MenuPluginsCreateRoute
  '/plugins': typeof MenuPluginsIndexRoute
  '/plugins/$pluginId': typeof MenuPluginsPluginIdPluginRouteWithChildren
  '/plugins/$pluginId/settings': typeof MenuPluginsPluginIdPluginSettingsRoute
}
export interface FileRoutesByTo {
  '/profile': typeof MenuProfileRoute
  '/': typeof MenuIndexRoute
  '/plugins/create': typeof MenuPluginsCreateRoute
  '/plugins': typeof MenuPluginsIndexRoute
  '/plugins/$pluginId': typeof MenuPluginsPluginIdPluginRouteWithChildren
  '/plugins/$pluginId/settings': typeof MenuPluginsPluginIdPluginSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_menu': typeof MenuRouteWithChildren
  '/_menu/profile': typeof MenuProfileRoute
  '/_menu/': typeof MenuIndexRoute
  '/_menu/plugins/create': typeof MenuPluginsCreateRoute
  '/_menu/plugins/': typeof MenuPluginsIndexRoute
  '/_menu/plugins/$pluginId': typeof MenuPluginsPluginIdRouteWithChildren
  '/_menu/plugins/$pluginId/_plugin': typeof MenuPluginsPluginIdPluginRouteWithChildren
  '/_menu/plugins/$pluginId/_plugin/settings': typeof MenuPluginsPluginIdPluginSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/'
    | '/plugins/create'
    | '/plugins'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/'
    | '/plugins/create'
    | '/plugins'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/settings'
  id:
    | '__root__'
    | '/_menu'
    | '/_menu/profile'
    | '/_menu/'
    | '/_menu/plugins/create'
    | '/_menu/plugins/'
    | '/_menu/plugins/$pluginId'
    | '/_menu/plugins/$pluginId/_plugin'
    | '/_menu/plugins/$pluginId/_plugin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MenuRoute: typeof MenuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_menu': {
      id: '/_menu'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu/': {
      id: '/_menu/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/profile': {
      id: '/_menu/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MenuProfileRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/plugins/$pluginId': {
      id: '/_menu/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof MenuPluginsPluginIdRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/plugins/': {
      id: '/_menu/plugins/'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof MenuPluginsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/plugins/create': {
      id: '/_menu/plugins/create'
      path: '/plugins/create'
      fullPath: '/plugins/create'
      preLoaderRoute: typeof MenuPluginsCreateRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/plugins/$pluginId/_plugin': {
      id: '/_menu/plugins/$pluginId/_plugin'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof MenuPluginsPluginIdPluginRouteImport
      parentRoute: typeof MenuPluginsPluginIdRoute
    }
    '/_menu/plugins/$pluginId/_plugin/settings': {
      id: '/_menu/plugins/$pluginId/_plugin/settings'
      path: '/settings'
      fullPath: '/plugins/$pluginId/settings'
      preLoaderRoute: typeof MenuPluginsPluginIdPluginSettingsRouteImport
      parentRoute: typeof MenuPluginsPluginIdPluginRoute
    }
  }
}

interface MenuPluginsPluginIdPluginRouteChildren {
  MenuPluginsPluginIdPluginSettingsRoute: typeof MenuPluginsPluginIdPluginSettingsRoute
}

const MenuPluginsPluginIdPluginRouteChildren: MenuPluginsPluginIdPluginRouteChildren =
  {
    MenuPluginsPluginIdPluginSettingsRoute:
      MenuPluginsPluginIdPluginSettingsRoute,
  }

const MenuPluginsPluginIdPluginRouteWithChildren =
  MenuPluginsPluginIdPluginRoute._addFileChildren(
    MenuPluginsPluginIdPluginRouteChildren,
  )

interface MenuPluginsPluginIdRouteChildren {
  MenuPluginsPluginIdPluginRoute: typeof MenuPluginsPluginIdPluginRouteWithChildren
}

const MenuPluginsPluginIdRouteChildren: MenuPluginsPluginIdRouteChildren = {
  MenuPluginsPluginIdPluginRoute: MenuPluginsPluginIdPluginRouteWithChildren,
}

const MenuPluginsPluginIdRouteWithChildren =
  MenuPluginsPluginIdRoute._addFileChildren(MenuPluginsPluginIdRouteChildren)

interface MenuRouteChildren {
  MenuProfileRoute: typeof MenuProfileRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenuPluginsCreateRoute: typeof MenuPluginsCreateRoute
  MenuPluginsIndexRoute: typeof MenuPluginsIndexRoute
  MenuPluginsPluginIdRoute: typeof MenuPluginsPluginIdRouteWithChildren
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuProfileRoute: MenuProfileRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenuPluginsCreateRoute: MenuPluginsCreateRoute,
  MenuPluginsIndexRoute: MenuPluginsIndexRoute,
  MenuPluginsPluginIdRoute: MenuPluginsPluginIdRouteWithChildren,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MenuRoute: MenuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
